### ISSUE TITLE
Cannot use extension

### ISSUE THREAD

**Issue by dreso** [innoverio/vscode-dbt-power-user#64] opened 2021-04-15 09:41 UTC
After updating to dbt 0.19 I cannot check Parent and Children models using the extension :/

**Comment by mdesmet** [comment] 2021-04-15 19:16
Could you provide more details? Which platform? Any errors in log (You can check the logs through https://stackoverflow.com/questions/30765782/what-is-the-use-of-the-developer-tools-in-vs-code#:~:text=2%20Answers&text=When%20you%20select%20the%20option,built%20with%20HTML%20and%20Javascript.)

**Comment by dreso** [comment] 2021-04-16 08:56
You mean the following? 
<img width="1239" alt="Screenshot 2021-04-16 at 10 53 52" src="https://user-images.githubusercontent.com/52713281/114999695-61584f00-9ea2-11eb-88fb-66658152dd8a.png">

**Comment by shr1k** [comment] 2021-04-20 14:18
I'm facing the same issue -- it looks like the extension fails to load, as I can't see it in my status bar at all. Here's a screenshot of the error in the dev console:

![image](https://user-images.githubusercontent.com/927606/115411690-98549a80-a1eb-11eb-9d83-f93cdab3149f.png)

**Comment by mdesmet** [comment] 2021-04-20 15:53
It's definitely a different error. In your case he extension is not able to be activated. If you can provide me with a minimal project, I can try to reproduce the issue.

**Comment by mdesmet** [comment] 2021-04-21 13:39
@shr1k : Your issue should be resolved with 0.5.3.

@dreso: Do you still have this issue? Does it happen in every project?

**Comment by shr1k** [comment] 2021-04-21 15:28
@mdesmet that was quick! :smile: it works now, thanks

**Comment by dreso** [comment] 2021-04-21 15:51
Yes still have it. It is the same for all projects unfortunately

**Comment by haf** [comment] 2021-09-02 12:42
Same here, nothing works. It starts and then gives *many* errors in the dev console but nothing actionable.

**Comment by mdesmet** [comment] 2021-09-02 12:49
Can you post the errors here?

**Comment by haf** [comment] 2021-09-03 08:48
It's a lot; like file not found errors, but it just started working in part.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/193115/131970025-ffbae427-b353-4a99-99b9-b7403eabc345.png">

**Comment by mdesmet** [comment] 2022-03-14 18:00
Can you guyst retest? Some of the issues look a lot like #57. Should be fixed with latest version.

**Closed** 2022-03-31 18:12 UTC
