### ISSUE TITLE
Runtime Error 'NoneType' object has no attribute 'find_generate_macro_by_name'

### ISSUE THREAD

**Issue by food-spotter** [innoverio/vscode-dbt-power-user#208] opened 2022-11-21 10:01 UTC
### Expected behavior

When trying to run any jinja templated SQL, the extension is able to compile the SQL and run the query correctly against the data warehouse

### Actual behavior

When trying to run any jinja templated SQL, the extension throws an error:

`Runtime Error 'NoneType' object has no attribute 'find_generate_macro_by_name'`

```json
{
  "code": -1,
  "message": "Runtime Error\n  Runtime Error\n    'NoneType' object has no attribute 'find_generate_macro_by_name'",
  "data": "\"Error: Traceback (most recent call last):\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 447, in compile_sql\\n    node = self.compile_node(self.get_server_node(raw_sql, temp_node_id))\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 373, in get_server_node\\n    sql_node = self.sql_parser.parse_remote(sql, node_name)\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 266, in sql_parser\\n    self._sql_parser = SqlBlockParser(self.config, self.dbt, self.config)\\n  File \\\"c:\\\\Users\\\\me\\\\Projects\\\\de-dbt\\\\.venv\\\\lib\\\\site-packages\\\\dbt\\\\parser\\\\base.py\\\", line 105, in __init__\\n    self._update_node_database = RelationUpdate(\\n  File \\\"c:\\\\Users\\\\me\\\\Projects\\\\de-dbt\\\\.venv\\\\lib\\\\site-packages\\\\dbt\\\\parser\\\\base.py\\\", line 74, in __init__\\n    macro = manifest.find_generate_macro_by_name(\\nAttributeError: 'NoneType' object has no attribute 'find_generate_macro_by_name'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 409, in execute_sql\\n    compilation_result = self.compile_sql(raw_sql)\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 451, in compile_sql\\n    raise RuntimeException(str(e))\\ndbt.exceptions.RuntimeException: Runtime Error\\n  'NoneType' object has no attribute 'find_generate_macro_by_name'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\node_python_bridge.py\\\", line 104, in <module>\\n    value = eval(_compile(data['code'], '<input>', 'eval'), _locals)\\n  File \\\"<input>\\\", line 1, in <module>\\n  File \\\"c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\dbt_integration.py\\\", line 418, in execute_sql\\n    raise RuntimeException(str(e))\\ndbt.exceptions.RuntimeException: Runtime Error\\n  Runtime Error\\n    'NoneType' object has no attribute 'find_generate_macro_by_name'\\n\\n\\tat ChildProcess.onMessage (c:\\\\Users\\\\me\\\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.10.1\\\\dist\\\\extension.js:4796:184)\\n\\tat Object.onceWrapper (node:events:646:26)\\n\\tat ChildProcess.emit (node:events:526:28)\\n\\tat emit (node:internal/child_process:938:14)\\n\\tat process.processTicksAndRejections (node:internal/process/task_queues:84:21)\""
}
```

### Steps To Reproduce

Exact steps to reproduce are not clear. It maybe environment specific

### Operating System

Windows 11 Pro. Version 10.0.22000 Build 22000

### dbt version

1.3.1

### dbt Adapter

dbt-snowflake

### dbt Power User version

0.10.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment] 2022-11-21 12:46
It is some issue with the manifest parsing. Is this an intermittent issue?

Could you try to create a dbt project that demonstrates the issue (For example using only seeds as datasources)?

**Comment by food-spotter** [comment] 2022-11-21 15:19
Local venv is created in VSCode (`CTRL`+`Shift`+`P`, "Python: Create Environment"). VSCode also shows it's using the correct interpreter (located within the venv).

We can execute any simple queries such as `SELECT 1,2` which bypass any templating.

**Comment by mdesmet** [comment] 2022-11-22 08:06
I understand. but on my side my test project works fine on Windows including jinja resolution.

Is this something that you have with every project? Could you try to create a minimally reproducible project and share it?

**Comment by sdepablos** [comment] 2022-11-24 12:34
@food-spotter have you tried `dbt clean` & `dbt deps`? In our case it solved the issue (happened to us right now)

**Comment by food-spotter** [comment] 2022-11-24 17:26
Thank you @sdepablos 🙌 that solved it!

**Comment by mdesmet** [comment] 2022-11-24 20:06
That's an actionable problem that can be detected by the extension. Thanks @sdepablos  for helping understand this.

I'll keep the issue open until I add detection for this issue and show a warning.

**Comment by bamorese** [comment] 2022-11-25 11:56
Hello, I have the same issue. Dbt clean or dbt deps did not solve it, still facing this: Runtime Error 'NoneType' object has no attribute 'find_generate_macro_by_name'. Do you have further advice?

**Comment by david-whimsical** [comment] 2022-12-02 13:52
If that helps anyone, I had the same problem and I solved it by creating a virtual environment _at the root_ of the dbt project. I am working with a monorepo, and my original folder structure was something like this:

```
monorepo_root/
├─ .gitignore
├─ folder1/
│  ├─ folder3/
│  │  ├─ ...
│  ├─ .virtualenv (does not work)/
│  ├─ the_dbt_project/
│  │  ├─ packages.yml
│  │  ├─ models/
│  │  │  ├─ pizza.sql
│  │  │  ├─ pasta.sql
│  │  │  ├─ schema.yml
│  │  ├─ ...
│  │  ├─ .virtualenv (works!)/
│  │  ├─ dbt_project.yml
├─ folder2/
│  ├─ ...
```

I'd open VSCode at the `/monorepo_root` level, and select the `.notworkingenv` virtual env. This wasn't working, I figure it's probably because the extension expects to find a `dbt_project.yml` file at the root?

I tried opening VSCode at the `/the_dbt_project` level, and created a new `.workingenv` virtual env, and it now works. Not super convenient though, since I need to edit stuff outside of the dbt project sometimes.

**Comment by mdesmet** [comment] 2022-12-02 22:11
That's weird though as the extension supports monorepo with multiple dbt projects (i use it quite often).

I usually put my venv in the root directory ./venv of the monorepo but that shouldn't matter I think...

**Comment by mtenenholtz** [comment] 2022-12-21 18:00
I also have this issue on macOS Venture 13.0.1. I'm using a conda environment, though.

**Comment by rubenhelsloot** [comment] 2022-12-30 15:59
FYI I had this issue as well and `dbt clean && dbt deps` did not solve it for me.

Turns out it was caused by a column definition being duplicated. I ran `dbt ls` at some point and got the following error:

```
Encountered an error:
Compilation Error
  dbt found two tests with the name "not_null_stg_promotion_supplier_contribution_sku" defined on column "sku" in "models.stg_promotion_supplier_contribution".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when running tests.
  
  To fix this, change the name of one of these resources:
  - test.pieter_pot_dwh.not_null_stg_promotion_supplier_contribution_sku.32d077df59 (models/staging/promotions/stg_promotions.yml)
  - test.pieter_pot_dwh.not_null_stg_promotion_supplier_contribution_sku.32d077df59 (models/staging/promotions/stg_promotions.yml)
```

And so I found the column and test that were duplicate. Hope this helps

**Comment by ValdarT** [comment] 2023-01-16 10:59
Our team was running into this on Github Codespaces - just disabling and reenabling the extension solved it so seems something at the setup stage.

**Comment by mdesmet** [comment] 2023-01-16 11:54
It might be a cache conflict. I'll dig into this in the next weeks.

**Comment by dave-coulter** [comment] 2023-01-26 03:01
> FYI I had this issue as well and `dbt clean && dbt deps` did not solve it for me.
> 
> Turns out it was caused by a column definition being duplicated. I ran `dbt ls` at some point and got the following error:
> 
> ```
> Encountered an error:
> Compilation Error
>   dbt found two tests with the name "not_null_stg_promotion_supplier_contribution_sku" defined on column "sku" in "models.stg_promotion_supplier_contribution".
>   
>   Since these resources have the same name, dbt will be unable to find the correct resource
>   when running tests.
>   
>   To fix this, change the name of one of these resources:
>   - test.pieter_pot_dwh.not_null_stg_promotion_supplier_contribution_sku.32d077df59 (models/staging/promotions/stg_promotions.yml)
>   - test.pieter_pot_dwh.not_null_stg_promotion_supplier_contribution_sku.32d077df59 (models/staging/promotions/stg_promotions.yml)
> ```
> 
> And so I found the column and test that were duplicate. Hope this helps

Similar fix here. Using `dbt ls`, I found a Description field in a yaml file was empty. When text was added (and it was no longer presenting as a "None is not of type string" error), the problem disappeared.

**Comment by wtfzambo** [comment] 2023-02-26 02:23
@mdesmet **Almost** same issue here, except I run into this problem when I click the "Compiled dbt preview" button, but none of the proposed fixes above worked for me.
I tried using the basic example that gets generated when running `dbt init` as well as another sample repo, and in both cases I got the same error.

I tried in WSL2 using Ubuntu-20.04, on Windows11 as well as in a VSCode Dev Container, each time I would get the same error.

The rest of the extension works properly (I can run and build models, execute queries, etc..) but the compiled preview doesn't.

dbt version = 1.4.3
extension version = 0.11.5

**Comment by sduck** [comment] 2023-02-26 09:37
I'm experiencing the exact same error on dbt version 1.4.3. However v1.3.2 works just fine.

I've tried with both Python 3.8.6, 3.9.16 and 3.10.10 and all results in the same: an error in the latest dbt version.

This is with a jaffle_shop demo

**Comment by mdesmet** [comment] 2023-02-26 09:55
dbt works, so it is rather the extension's compatibility. To figure out what needs to be done we need to find out the yaml or json piece that is causing trouble.

**Comment by wtfzambo** [comment] 2023-02-26 12:49
@mdesmet anythink any way we can help you with this task?

**Comment by campbellfleury** [comment] 2023-02-27 03:43
Same issue for me after upgrades to 1.4.3 for core and adapters. Rolled my environment back dbt-core==1.4.1 dbt-databricks==1.4.1 dbt-postgres==1.4.1. Retained v 0.11.5 of dbt Power User and back I'm back up and running. This was occuring both on my MacOS and Windows environments.

**Comment by mdesmet** [comment] 2023-02-27 08:48
Thanks, that's a good pointer. I'll try to fix it.

**Comment by campbellfleury** [comment] 2023-02-27 20:12
It's a great extension, keep up the good work.

**Comment by mdesmet** [comment] 2023-02-27 22:19
Fixed in 0.11.6, fix should be backwards compatible.

Let me know if it works.

**Comment by sduck** [comment] 2023-02-28 07:11
Works for me. Thanks a lot @mdesmet 💪

**Comment by mdesmet** [comment] 2023-02-28 07:49
Thanks for helping to troubleshoot the issue! If the extension helps you, please rate us on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Closed by mdesmet** 2023-02-28 07:49 UTC
Labels: bug

**Comment by wtfzambo** [comment] 2023-02-28 09:57
Works perfectly now, thanks for the quick fix!

**Comment by sduck** [comment] 2023-03-17 07:25
Using the Command Palette in VSCode, you can run the "Check for extension updates" command. From there you should be able to see and install the update

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1327028/225839479-40612a90-3be1-427a-8235-15125f263aae.png">

**Comment by AlessandraFaria** [comment] 2023-03-22 13:54
i am using the following configurations and i still have the error
 dbt-core core: 1.3.3
 dbt-redshift: 1.3.0
 dbt-postgres:  1.3.3
 dbt Power User: 0.11.6
 python: 3.9.5
 VSCode: 1.76.2

**Comment by facuz-wallapop** [comment] 2023-03-31 08:29
I've the same issue on Mac OS Ventura.

dbt-core; 1.3.1
dbt power user: 0.11.6
python: 3.9.10 (venv)

**Comment by adambalila** [comment] 2023-03-31 13:28
I was able to fix the problem with edit the vscode setting.json file and adding this section (this specific settings is for macOS, if you have issues with the Windows you will need to use `terminal.integrated.env.windows`)
`"terminal.integrated.env.osx": {
    "DBT_ENV_HASH_SALT": [hash_key_value],
    "DBT_PROFILES_DIR": [.dbt location library]
}`

**Comment by astephan-mm** [comment] 2023-04-17 07:54
Hello,

I had a colleague who had the same problem. Turns out she was launching VSCode straight from her /Downloads folder, she had never moved the application into the /Applications folder. The issue was solved by moving the app into the /Applications folder.

**Comment by Thootje** [comment] 2023-05-05 07:40
It seems this error often occurs whenever there is an issue in your DBT project, however the extension isn't specific about what is wrong. I tried these earlier suggestions:
- Double-checked I was using the right interpreter.
- Run `dbt clean && dbt deps`. 
- Run `dbt ls` and checked for warnings.

Those didn't work for me, but my issue was that the extension didn't use the environment variables that are included in my DBT project (env_var('')) which I provided in my virtual environment. After providing my ENV variables to `terminal.integrated.env.osx` it did work:

```
    "terminal.integrated.env.osx": {
        "DBT_DEPLOY_ENV": "feature",
        "DBT_PROJECT_GCP": "*******"
    }
```

**Comment by andrejnevesjr** [comment] 2023-05-05 09:31
Same situation as https://github.com/Thootje,

I figure out that was required to use one variable that the extension didn't find declare on my dbt_project.yml, so setting all variables required to `terminal.integrated.env.osx` solved the issue :) 


`    "terminal.integrated.env.osx": {
        "VAR1": "Value",
        "VAR2": "Value"
    }`
    
   Just added it and perform the compile again.... working so far so good

**Comment by analimaps** [comment] 2023-05-23 03:24
> Hello,
> 
> I had a colleague who had the same problem. Turns out she was launching VSCode straight from her /Downloads folder, she had never moved the application into the /Applications folder. The issue was solved by moving the app into the /Applications folder.

Thanks, your comment helped me solve this issue!

**Comment by jonasmmiguel** [comment] 2023-08-23 13:20
I ran into the same error. Running my model from the CLI (`dbt run`) pointed me to the actual underlying cause, which was a duplicated column definition in a yml. 

@mdesmet, could we somehow show the error message given by `dbt run` in such cases, instead of the `NoneType` above?

**Comment by Terroface** [comment] 2023-08-25 07:42
I ran into this error, tried all the fixes above, and nothing worked. 

It was working fine until I added an environment variable import to one of my `source.yml` files. Might I need to do something to enable the extension to read from my local `.env` file?

Note: `.env` is not located where my `dbt_project.yml` is located. Instead, it's one subfolder down. I cannot move it up, because dagster relies on that location.

**Comment by aendreas** [comment] 2023-11-08 09:38
Should you encounter this issue, and the dbt tab in VS Code > Project Actions > Project Health Check lists problems with environment variables, you can easily solve this by adding these in settings.json:

`terminal.integrated.env.windows": {
        "DB_SCHEMA": "some_schema",
        "DB_NAME": "some_name",
        "DB_HOST" : "some_host"
    }`

**Comment by rendybjunior** [comment] 2023-12-20 00:18
reinstalling the extension somehow works for me

**Comment by lassebenni** [comment] 2024-01-04 13:31
> reinstalling the extension somehow works for me

Only thing that worked for me too, unfortunately.
